apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: l2-net1
  namespace: default
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "bridge",
    "bridge": "br0",
    "ipam": {
      "type": "static",
      "addresses": [
        {
          "address": "10.10.0.10/24",
          "gateway": "10.10.0.1"
        }
      ]
    }
  }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: l2-net2
  namespace: default
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "bridge",
    "bridge": "br1",
    "ipam": {
      "type": "static",
      "addresses": [
        {
          "address": "10.20.0.10/24",
          "gateway": "10.20.0.1"
        }
      ]
    }
  }'
